logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: ERROR
    org.apache.commons.beanutils: ERROR

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  datasource:
    url: jdbc:mysql://lhcp3004.webapps.net:3306/n63o4crk_monopoli
    username: n63o4crk_guest
    password: patriziopezzilli
    driverClassName: com.mysql.cj.jdbc.Driver
  
server:
  port: 8888
  servlet :
    context-path :  /monopoli-be/api

management:
  server:
    port: 8081
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true

  
